const { app, BrowserWindow } = require('electron');
const http = require('node:http');
const fs = require('node:fs');
const path = require('node:path');
const assert = require('node:assert/strict');
const { randomUUID } = require('node:crypto');
app.setPath('userData', path.join(__dirname, '..', '.design-smoke-data', randomUUID()));
let nextID = 0;
const server = http.createServer((req, res) => {
  let body = ''; req.on('data', chunk => { body += chunk; }); req.on('end', () => {
    const data = req.url === '/api/login' ? { token: 'fixture-token' } : req.url === '/api/account/add' ? { accountId: ++nextID, email: JSON.parse(body).email } : { list: [] };
    res.setHeader('Content-Type', 'application/json'); res.end(JSON.stringify({ code: 200, data }));
  });
});
server.listen(18766, '127.0.0.1'); require('../src/main');
const sleep = ms => new Promise(resolve => setTimeout(resolve, ms));
async function waitFor(fn) { for (let i = 0; i < 100; i++) { if (await fn()) return; await sleep(100); } throw new Error('Timed out'); }
app.whenReady().then(async () => {
  try {
    let manager;
    await waitFor(() => { manager = BrowserWindow.getAllWindows().find(w => w.webContents.getURL().endsWith('/index.html')); return manager && !manager.webContents.isLoading(); });
    const errors = []; manager.webContents.on('console-message', (_event, level, message) => { if (level === 3) errors.push(message); });
    const invoke = script => manager.webContents.executeJavaScript(script);
    const first = await invoke("window.sites.add({name:'即梦工作室',url:'https://jimeng.jianying.com'})");
    const second = await invoke("window.sites.add({name:'Dreamina 海外',url:'https://dreamina.capcut.com'})");
    await invoke(`window.accounts.add({siteId:'${first.site.id}',name:'15528949706',note:'主账号',openNow:false})`);
    await invoke(`window.accounts.add({siteId:'${first.site.id}',name:'studio@shibox.cloud',note:'设计团队',openNow:false})`);
    const config = { baseURL: 'http://127.0.0.1:18766', adminEmail: 'admin@example.test', password: 'fixture-secret', domain: 'shibox.cloud', prefix: 'qf' };
    await invoke(`window.cloudMail.save(${JSON.stringify(config)})`);
    await invoke("document.getElementById('add').click()");
    assert.equal(await invoke("document.getElementById('dialog').open"), true);
    assert.equal(await invoke("document.getElementById('manual-fields').hidden"), false);
    await invoke(`document.getElementById('account-site').value='${second.site.id}';document.getElementById('account-site').dispatchEvent(new Event('change'));document.getElementById('name').value='team@shibox.cloud';document.getElementById('account-note').value='内容团队';document.getElementById('open-now').checked=false;document.getElementById('form').requestSubmit()`);
    await waitFor(() => invoke("!document.getElementById('dialog').open"));
    let state = await invoke('window.accounts.list()'); assert.equal(state.accounts.length, 3); assert.equal(state.accounts[2].siteId, second.site.id);
    await invoke("document.getElementById('add').click();document.getElementById('mode-auto').click()");
    await waitFor(() => invoke("document.getElementById('generate-domain').value==='shibox.cloud'"));
    assert.equal(await invoke("document.getElementById('name').required"), false);
    await invoke(`document.getElementById('account-site').value='${second.site.id}';document.getElementById('generate-prefix').value='creative';document.getElementById('generate-count').value='2';document.getElementById('account-note').value='创作账号';document.getElementById('open-now').checked=false;document.getElementById('form').requestSubmit()`);
    await waitFor(() => invoke("!document.getElementById('dialog').open"));
    state = await invoke('window.accounts.list()'); assert.equal(state.accounts.length, 5); assert.equal(state.accounts.filter(a => a.siteId === second.site.id).length, 3);
    assert.ok(state.accounts.at(-1).mail.email.startsWith('creative-'));
    await invoke(`window.sites.edit({id:'${first.site.id}',name:'即梦设计工作室',url:'https://jimeng.jianying.com'})`);
    await invoke('(async()=>render(await window.accounts.list()))()');
    assert.equal(await invoke("document.querySelectorAll('.site-group').length"), 2);
    assert.equal(await invoke("document.querySelectorAll('.account-row .avatar svg').length"), 5);
    assert.equal(await invoke("document.querySelectorAll('.copy-account-button svg').length"), 5);
    await invoke("document.getElementById('toast').classList.remove('show')");
    await sleep(300);
    await manager.webContents.capturePage().then(img => fs.writeFileSync(path.join(__dirname, '..', 'website-dashboard-preview.png'), img.toPNG()));
    await invoke(`selectedSite='${second.site.id}';render()`); assert.equal(await invoke("document.querySelectorAll('.site-group').length"), 1);
    await invoke("selectedSite=null;render();document.getElementById('search').value='即梦设计';document.getElementById('search').dispatchEvent(new Event('input'))");
    assert.equal(await invoke("document.querySelectorAll('.account-row').length"), 2);
    await invoke("document.getElementById('search').value='';render();document.getElementById('add').click();document.getElementById('mode-auto').click()");
    await invoke(`document.getElementById('account-site').value='${second.site.id}';document.getElementById('account-site').dispatchEvent(new Event('change'));document.getElementById('generate-prefix').value='creative';document.getElementById('account-note').value='设计团队'`);
    await invoke("document.getElementById('toast').classList.remove('show')");
    await sleep(300);
    assert.equal(await invoke("window.innerWidth < 1100 || document.querySelector('main').getBoundingClientRect().right <= document.getElementById('dialog').getBoundingClientRect().left + 1"), true, 'drawer must not cover the dashboard at desktop widths');
    assert.equal(await invoke("document.getElementById('submit').getBoundingClientRect().bottom <= window.innerHeight"), true, 'drawer footer remains visible');
    assert.equal(await invoke("Array.from(document.querySelectorAll('.account-row')).every(row=>row.querySelector('.row-controls').getBoundingClientRect().right<=row.getBoundingClientRect().right)"), true, 'all account actions fit in their rows');
    assert.equal(await invoke("document.querySelector('main').scrollWidth<=document.querySelector('main').clientWidth"), true, 'dashboard never overflows horizontally');
    await manager.webContents.capturePage().then(img => fs.writeFileSync(path.join(__dirname, '..', 'website-groups-preview.png'), img.toPNG()));
    await invoke("document.getElementById('new-site').click()");
    assert.equal(await invoke("document.getElementById('sites-dialog').open"), true);
    await invoke("document.getElementById('site-name').value='内容工具';document.getElementById('site-url').value='https://example.com';document.getElementById('site-form').requestSubmit()");
    await waitFor(() => invoke("!document.getElementById('sites-dialog').open"));
    assert.equal((await invoke('window.accounts.list()')).sites.length, 3);
    assert.equal(await invoke("document.getElementById('account-site').selectedOptions[0].textContent"), '内容工具');
    assert.equal(await invoke("document.getElementById('mail-generate')"), null, 'only one add entry');
    await invoke("document.getElementById('dialog').close()");
    manager.setSize(1000, 760); await sleep(300);
    assert.equal(await invoke("document.querySelector('main').scrollWidth<=document.querySelector('main').clientWidth"), true, 'narrow desktop dashboard does not overflow');
    await invoke("document.getElementById('add').click()"); await sleep(300);
    assert.equal(await invoke("document.getElementById('submit').getBoundingClientRect().bottom<=window.innerHeight"), true, 'small window footer remains reachable');
    assert.deepEqual(errors, []);
    console.log('PASS: website CRUD, grouped rows, sidebar and search, unified manual/auto form, prefix generation, nested website creation');
    server.close(); app.quit();
  } catch (error) { console.error(error); server.close(); app.exit(1); }
});
